name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          2.7,
          3.5,
          3.6,
          3.7
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libkrb5-dev
          pip install .[tests]
      - name: Run tests
        run: |
          pytest -s tests/ integration_tests/
